### PR TITLE
Making the Editor respect keywords separator

### LINKED ISSUE #13: Editor doesn't respect keywords separator
When a document (in my use/test case, a PDF document) that has already been tagged and has more than one keyword added to it, gets opened in the editor, the editor separates the keywords with ';' regardless of what character is used/saved as the separator for the keywords.

This creates a problem, because when you open an already tagged document to change something, if you have a preference/need for a certain type of keyword separator, you have to change the keyword field, otherwise on save, regardless of what change has been made, the editor will override the keyword field and now the keywords will be separated by ';'.

What should happen instead, is the editor should show the keywords in the keywords field, separated by the separator character already used.

### PR DESCRIPTION
**Pull request by ifohancroft**
This fixes #13

### CODE REVIEW

**Comment by ifohancroft** [comment]
The branch got a bit behind master and while it was still possible to merge it without conflicts, it was annoying me, so I merged master into it.

**Comment by ifohancroft** [comment]
Bump :D

**Comment by glutanimate** [comment]
Alright, thanks for the clarification on the separator (and the reminder :smile: ). All looks good I think. Thanks again!

**Comment by ifohancroft** [comment]
Most welcome and thank you too!

**Pull request merged**
